#ifndef __LIBOROBI_COMMON_H__
#define __LIBOROBI_COMMON_H__

typedef enum {
    OROBI_OK = 0,
    OROBI_ERROR_INVALID_INPUT = -1,
    OROBI_ERROR_PACKET_TOO_OLD = -2,
    OROBI_ERROR_NONCE_REPLAY = -3,
    OROBI_ERROR_ENCRYPTION_FAILED = -4,
    OROBI_ERROR_DECRYPTION_FAILED = -5,
    OROBI_ERROR_HASH_MISMATCH = -6,
    OROBI_ERROR_PACKET_VALIDATION_FAILED = -7,
    OROBI_ERROR_MEMORY = -8,
    OROBI_ERROR_INITIALIZATION_FAILED = -9,
    OROBI_ERROR_TIME_SYNC = -10,
    OROBI_ERROR_DEPENDENCY_MISSING = -11,
    OROBI_ERROR_BUFFER_OVERFLOW = -12,
    OROBI_ERROR_INVALID_CONFIGURATION = -13,
    OROBI_ERROR_CRYPTOGRAPHIC_FAILURE = -14,
    OROBI_ERROR_INVALID_COMMAND = -15,
    OROBI_ERROR_COMMAND_OVERFLOW = -16,
    OROBI_ERROR_UNSUPPORTED_COMMAND = -17
} orobi_error_t;


typedef union {
    struct {
        uint64_t              high;
        uint64_t              low;
    };
    uint64_t    key[2];
} uint128_t;


#endif
